import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { AlarmProvider } from "@/contexts/AlarmContext";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Alarm Clock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AlarmProvider>
            {children}
            <Toaster />
          </AlarmProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
